
services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    depends_on:
       db:
         condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: